# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='phone',
        ),
    ]
