# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=50)),
                ('discript', models.CharField(max_length=256)),
                ('sale', models.CharField(max_length=20)),
                ('com', models.CharField(max_length=20)),
            ],
        ),
    ]
