# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181106_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=50)),
                ('discript', models.CharField(max_length=256)),
                ('sale', models.CharField(max_length=20)),
                ('com', models.CharField(max_length=20)),
            ],
        ),
    ]
