# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
